// File generated by FlutterFire CLI.
// This is a placeholder file. You need to run `flutterfire configure` to generate the actual file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYtRKyYoGksEe4lqe_1QkNZwpdufqDmw',
    appId: '1:250725613501:web:2b651eee8a10b6f63d5cd4',
    messagingSenderId: '250725613501',
    projectId: 'edgeup-upsc-app',
    authDomain: 'edgeup-upsc-app.firebaseapp.com',
    storageBucket: 'edgeup-upsc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WxGILV1NnY1go29gKYBwyKRgqJ8H-ls',
    appId: '1:250725613501:android:86992b670984195d3d5cd4',
    messagingSenderId: '250725613501',
    projectId: 'edgeup-upsc-app',
    storageBucket: 'edgeup-upsc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4SnvBfzV-1iiv3XRcpS2ee39mS2lVP8',
    appId: '1:250725613501:ios:335bf451852eb8e03d5cd4',
    messagingSenderId: '250725613501',
    projectId: 'edgeup-upsc-app',
    storageBucket: 'edgeup-upsc-app.firebasestorage.app',
    iosBundleId: 'com.edgeup.edgeupUpscApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4SnvBfzV-1iiv3XRcpS2ee39mS2lVP8',
    appId: '1:250725613501:ios:335bf451852eb8e03d5cd4',
    messagingSenderId: '250725613501',
    projectId: 'edgeup-upsc-app',
    storageBucket: 'edgeup-upsc-app.firebasestorage.app',
    iosBundleId: 'com.edgeup.edgeupUpscApp',
  );

}